### ISSUE TITLE
Plug option add 'not for' for not using a plug when filetype = 

### ISSUE THREAD

**Issue by cxwx** [junegunn/vim-plug#965] opened 2020-05-03 12:27 UTC
Plug option add 'not for' for not using a plug when filetype = 
e.g.
    Plug 'mtth/cursorcross.vim', {'not for', 'org'}

------------------------------

lastest

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [X] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [X] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by junegunn** [comment] 2020-05-03 13:02
Duplicate of #928

**Closed by junegunn** 2020-05-03 13:02 UTC
Labels: duplicate
