### ISSUE TITLE
MacVim 7.4 hangs during :PlugInstall and :PlugUpdate

### ISSUE THREAD

**Issue by jawhiteley** [junegunn/vim-plug#356] opened 2015-12-13 18:46 UTC
When running either :PlugInstall or :PlugUpdate from within the MacVim gui, everything appears to finish, but there is no "Finished" message, and the window becomes unresponsive; <C-C> does not do anything. The plugins do seem to be installed, however, so everything works fine after quitting and restarting MacVim (no need to force-quit, but I do have to quit MacVim and all open windows). Other windows are unaffected.

These commands work fine in MacVim 7.3 and vim in the terminal (7.3 compiled by apple).
However, I need vim 7.4 to run the vim-r-plugin. :/

I seem to remember seeing references to "screen freeze / hang" in earlier versions of vim-plug - is this related?

Screenshots attached (the second is what it looks like when trying to resize the window).
Can this be addressed within vim-plug?
Should I report this to the MacVim developers? If so, what should I tell them?

![screen shot 2015-12-13 at 1 42 59 pm](https://cloud.githubusercontent.com/assets/1281318/11768589/c7ca4a82-a19f-11e5-948d-671227659900.png)

![screen shot 2015-12-13 at 1 43 30 pm](https://cloud.githubusercontent.com/assets/1281318/11768590/cca6ff78-a19f-11e5-93c4-a6e29be58ced.png)

**Comment by junegunn** [comment] 2015-12-14 03:21
I tested with MacVim installed with homebrew (`macvim: stable 7.4-84, HEAD`) but I can't reproduce the problem.
- How did you install MacVim? `brew install macvim`?
- Which version do you have?

**Comment by jawhiteley** [comment] 2015-12-14 03:31
I did not install it from homebrew, but from the dmg here:
https://github.com/macvim-dev/macvim/releases/tag/snapshot-86

:version starts with
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  7 2015 04:55:17)
MacOS X (unix) version
Included patches: 1-963
Compiled by travis@Traviss-Mac-188.local

I have been meaning to start using homebrew, so this might be a good opportunity. I will try homebrew and let you know, although it might take a couple of days. Thank you for looking into it.

**Comment by jawhiteley** [comment] 2015-12-14 04:34
I updated Homebrew on my system, and installed macvim using `brew install macvim`.
I had no problems running :PlugUpdate or :PlugInstall in the Homebrew version of MacVim (`macvim: stable 7.4-85, HEAD`).

Nevertheless, I noticed that Homebrew was pulling from snapshot 85:
  ==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-85.tar.gz
Whereas I was having problems with the version from snapshot 86 (link in my previous comment). Does this mean that when macvim is updated to snapshot 86 on Homebrew, this problem will appear?

The problem is solved for me, anyway - and I got my feet wet with Homebrew, which is pretty cool! I will leave it to you whether you consider it closed or not.

Thank you.

**Comment by junegunn** [comment] 2015-12-14 14:06
> Does this mean that when macvim is updated to snapshot 86 on Homebrew, this problem will appear?

It's probable. But I just tested snapshot 86 on my machine and couldn't reproduce the problem. So I guess we can close this for now. Please let me know if you see this problem again in the future. Thanks.

**Closed by junegunn** 2015-12-14 14:06 UTC
