### ISSUE TITLE
No colors when compiling YCM through Vim-Plug on Neovim

### ISSUE THREAD

**Issue by ladislas** [junegunn/vim-plug#248] opened 2015-06-15 12:39 UTC
I use vim-plug to manage my plugins and it works great with neovim (that I love)

The only minor issue I have is that when compiling YCM, I don't get the colored output I was used to.

![](https://cloud.githubusercontent.com/assets/2206544/8154049/6664055a-1336-11e5-903d-4175e1ddcea8.png)

It is only aesthetics but I thought you should know :)

**Comment by junegunn** [comment] 2015-06-15 13:21
Thanks for letting me know, but it's a duplicate of #209. You can also tell the neovim guys to fix it from their side :)

**Closed by junegunn** 2015-06-15 13:21 UTC

**Comment by ladislas** [comment] 2015-06-15 13:34
just did, thanks

**Comment by ladislas** [comment] 2015-06-24 05:43
Just to let you know:

> Are you compiling it via :term, or are you using a vim-plug "do" post-install handler? If the latter, then it can be addressed if vim-plug uses :term instead of :! or system().

**Comment by junegunn** [comment] 2015-06-24 10:40
So they decided not to fix the issue from their side. Unfortunately, we probably aren't going to address it either as we want to avoid adding more neovim-specific code to vim-plug. See the discussion at #209.
