### ISSUE TITLE
PlugInstall "invalid reference to master"

### ISSUE THREAD

**Issue by andykais** [junegunn/vim-plug#1023] opened 2020-10-12 19:14 UTC
github is going through a renaming process where the default branch on many repos is changing from `master` to `main`  https://github.com/github/renaming. This appears to be a problem for plug, as it hardcodes the default branch as master. I experienced this when installing vim-svelte
<img width="414" alt="Screen Shot 2020-10-12 at 3 08 56 PM" src="https://user-images.githubusercontent.com/6627147/95782002-e3ba4900-0c9c-11eb-880e-f3f8d79e553e.png">
I am guessing this is a bug for vim-plug and not for vim-svelte & any other repos accepting the naming change. This can be fixed by setting
```vimscript
Plug 'evanleck/vim-svelte', { 'branch': 'main' }
```
but I believe several packages will run into this issue going forward

------------------------------

```
:version
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG
 -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion
-Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATE
D_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs
/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20
190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Conten
ts/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs
/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by janlazo** [comment] 2020-10-12 19:16
Duplicate of https://github.com/junegunn/vim-plug/issues/1023. Comment there instead.

**Closed by janlazo** 2020-10-12 19:16 UTC
