### ISSUE TITLE
Neovim Remote Plugins

### ISSUE THREAD

**Issue by vito-c** [junegunn/vim-plug#330] opened 2015-11-26 18:19 UTC
Does vim-plug work with neovims remote plugins? Does it call `UpdateRemotePlugins` after loading? I've had issues getting https://github.com/ensime/ensime-vim/ to work

**Comment by vheon** [comment] 2015-11-26 19:14
I think this is a duplicate of #125

**Comment by starcraftman** [comment] 2015-11-26 19:21
@vito-c Hi, see #125 for our discussion. Seems we left off waiting to see if the API would change again (i.e. not need UpdateRemotePlugins). So no support at present. I can imagine that might be inconvenient. Maybe time to revisit.

**Comment by starcraftman** [comment] 2015-11-26 19:35
I'll close this for now, please follow the other thread for updates @vito-c

**Closed by starcraftman** 2015-11-26 19:35 UTC
Labels: duplicate

**Comment by junegunn** [comment] 2015-11-27 16:33
@vheon @starcraftman Thanks guys.

@vito-c Note that the installation instruction of the plugin clearly states that a manual `UpdateRemotePlugins` is required.
