### ISSUE TITLE
Feature request: a NOT 'for' build spec option

### ISSUE THREAD

**Issue by equwal** [junegunn/vim-plug#1060] opened 2021-01-19 16:07 UTC
Thank you for vim-plug, I have very efficiently gone from a fast vim startup to a slow one.

My suggestion to improve this is to avoid loading things on certain uses of vim. I use [nvimpager](https://github.com/lucc/nvimpager) as my manpage viewer, so I don't need any completion or whatever. I propose this construct:

```vim
Plug 'tpope/vim-surround' {'notfor':'man'} " don't load if only in man mode pager
```

In this way I would load my pager much faster, since I want almost no plugins.

**Comment by equwal** [comment] 2021-01-19 16:10
I'm currently working on some cheap hack to use `'on'` for this

**Comment by equwal** [comment] 2021-01-19 17:13
Okay, this hack works:
```vimL
fun! AntiManTrigger()
    " Trigger lazy pakage load.
endfunction

fun! AntiMan()
  if &ft != 'man'
     call AntiManTrigger()
  endif
endfunction

command -nargs=* AntiManCom call AntiMan()

au VimEnter * AntiManCom
call plug#begin('~/.config/nvim/plugged')
    Plug 'bling/vim-airline', {'on':'AntiManTrigger'}
call plug#end()
```

**Comment by equwal** [comment] 2021-01-19 17:35
Actually, it doesn't work, though I don't know why (yet).

**Comment by junegunn** [comment] 2021-01-20 01:08
Duplicate of #928.

Shouldn't `{'on':'AntiManTrigger'}` be `{'on':'AntiManCom'}`?

**Closed by junegunn** 2021-01-20 01:08 UTC
Labels: enhancement
