### ISSUE TITLE
Error when executing PlugClean

### ISSUE THREAD

**Issue by TravisCao** [junegunn/vim-plug#1022] opened 2020-10-10 07:09 UTC
Explain the problem here ...

Error happened when executing PlugClean. It said can't open temp file but the file doesn't exist. 
![image](https://user-images.githubusercontent.com/35266867/95648526-855d6100-0b0a-11eb-8748-6dae1b93ad5a.png)
------------------------------

```
![image](https://user-images.githubusercontent.com/35266867/95648543-a45bf300-0b0a-11eb-9aec-1c1a5d305771.png)
```

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [X] Windows
- Vim:
    - [ ] Terminal Vim
    - [X] GVim
    - [ ] Neovim

**Comment by janlazo** [comment] 2020-10-10 13:58
Same core issue occuring in https://github.com/junegunn/vim-plug/issues/852, https://github.com/junegunn/vim-plug/issues/919.

What is vim version?

**Comment by janlazo** [comment] 2020-10-30 13:04
Treating this as a duplicate of those tickets.

**Closed by janlazo** 2020-10-30 13:04 UTC
