### ISSUE TITLE
s:system tries to delete non-existent batchfile

### ISSUE THREAD

**Issue by jdhao** [junegunn/vim-plug#900] opened 2019-11-01 02:35 UTC
I am using the latest version of vim-plug on Windows 10. I have noticed that after I open the nvim-qt window for some time (I do not know exact time, maybe more than 10 hours?). When I use `PlugUpdate`, the following errors occurs:

```
|| Error detected while processing function
|| <SNR>7_update[1]
|| <SNR>7_update_impl[108]
|| <SNR>7_update_vim[4]
|| <SNR>7_tick[21]
|| <SNR>7_git_validate[3]
|| <SNR>7_system[11]
|| E121: Undefined variable: batchfile
|| E116: Invalid arguments for function delete
|| Error detected while processing function
|| <SNR>7_update[1]
|| <SNR>7_update_impl[108]
|| <SNR>7_update_vim[4]
|| <SNR>7_tick[21]
|| <SNR>7_git_validate[3]
|| E171: Missing :endif
|| Error detected while processing function
|| <SNR>7_update[1]
|| <SNR>7_update_impl[108]
|| <SNR>7_update_vim[4]
|| <SNR>7_tick[21]
|| E171: Missing :endif
|| Error detected while processing function
|| <SNR>7_update[1]
|| <SNR>7_update_impl[108]
|| E171: Missing :endif
```

It only happens after I open nvim-qt for some time. If I quit it, reopen and use `PlugUpdate` command, nothing wrong happens. I have tried to run `PlugInstall` or `PlugStatus` or `PlugUpgrade`. All the command gives similar errors that the variable `batchfile` is not defined.

------------------------------

The output of `:version`

```
NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by janlazo** [comment] 2019-11-01 03:57
Isn't this a duplicate of https://github.com/junegunn/vim-plug/issues/852?

**Comment by jdhao** [comment] 2019-11-01 04:07
I am not sure... In this case, the error is that `batchfile` variable is not defined. In that issue, it is the temp file not found...

I am not familiar with the vim-plug code.

**Comment by janlazo** [comment] 2019-11-01 06:16
The code assumes that `batchfile` is always defined but `tempname` or `writefile` can fail. Adding a check if the batchfile value is valid should fix it any maybe catching the error.

**Closed** 2019-11-04 02:10 UTC
Labels: bug, neovim
