### ISSUE TITLE
VIM-PLUG Not Work for NeoVIM with SpaceVIM

### ISSUE THREAD

**Issue by anson2416** [junegunn/vim-plug#743] opened 2018-03-08 13:55 UTC
Follow the steps of vim-plug project in GitHub, NeoVIM is not able to start up.

Error Message:
`Neovim is taking too long to respond`.
------------------------------

```
OS: Win 10 64bit
NeoVim: v0.2.2
```

- Type:
    - [x] **Bug**
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question

- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] **Windows**
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] **Neovim**

**Comment by janlazo** [comment] 2018-04-05 15:59
Are you using the python/ruby/node provider? That startup issue is likely caused by the GUI or plugin using RPC, not vim-plug.

**Comment by janlazo** [comment] 2019-08-16 22:10
https://github.com/junegunn/vim-plug/pull/860 is merged which should mitigate the performance issue on Neovim. It's not fully optimized yet but it should be fast enough to avoid this error. Please reply back if this remains an issue. Thanks.

**Closed by janlazo** 2019-08-16 22:10 UTC
