### ISSUE TITLE
D (view changes log) opens empty window (Startify compatibility problem).

### ISSUE THREAD

**Issue by kwinczek** [junegunn/vim-plug#426] opened 2016-02-26 09:57 UTC
After :PlugUpdate executed from Startify window, when some updates were pulled vim-plug does open an empty vertical split to the right after pressing D to display changes log. That does not happen when no Startify window is present.

```
NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-pa
rameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DEC
LARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160222-36194-1mereup/neovim-0.1.2/build/config -I/tmp/neovim20160222-36194-1m
ereup/neovim-0.1.2/src -I/tmp/neovim20160222-36194-1mereup/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160222-3
6194-1mereup/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160222-36194-1mereup/neovim-0.1.2/deps-build/usr/inclu
de/luajit-2.0 -I/tmp/neovim20160222-36194-1mereup/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160222-36194-1mer
eup/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160222-36194-1mereup/neovim-0.1.2/deps-build/usr/include -I/tmp
/neovim20160222-36194-1mereup/neovim-0.1.2/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/u
sr/include -I/tmp/neovim20160222-36194-1mereup/neovim-0.1.2/build/src/nvim/auto -I/tmp/neovim20160222-36194-1mereup/ne
ovim-0.1.2/build/include

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.2/share/nvim"
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment] 2016-02-26 14:47
@mhinz Do you know why this happens?

1. Start vim with no arg
1. We see startify window (buffer num: 1)
1. `PlugInstall` opens vertical split (buffer num: 2)
1. Doing `PlugInstall` again replaces buf 2 with empty buf 3 and opens another split for the installer

**Comment by mhinz** [comment] 2016-02-26 14:58
Hmm, it seems that `s:prepare()` calls `s:new_window()` which does:

```vim
  execute get(g:, 'plug_window', 'vertical topleft new')
```

And there's no `g:plug_window` after doing `:PlugInstall`. :-)

**Comment by junegunn** [comment] 2016-02-26 15:19
@mhinz Okay, we don't even need vim-plug in this picture.

1. vim with no args
2. startify window
3. `new` to open a split
4. `bd` does not close the split

I don't know if it's the expected behavior or not, but that's what's causing the extra split window.

**Comment by junegunn** [comment] 2016-02-26 15:28
I just remembered a related issue regarding startify:
https://github.com/junegunn/fzf/issues/225

**Comment by mhinz** [comment] 2016-02-26 15:28
Hmm, it seems that `:bd` won't close the last listed buffer.

1. `vim -u NONE -N`
1. `:set buflisted`
1. `:new`
1. `:bd` won't close the buffer (and therefore the window)

**Comment by junegunn** [comment] 2016-02-26 15:35
Yeah, that's what I noticed in the above issue, that I just remembered.
Here I can simply change `bd` to `close`, since `bufhidden` of plug window is already "wipe".

**Comment by junegunn** [comment] 2016-02-26 15:47
Hmm, nope, that is not ideal when `let g:plug_window = 'enew'`.

@kwinczek I think I'm just gonna close this issue as wontfix since it's not really critical and the solution is going to be unnecessarily complex. Sorry about that but thanks for letting me know of the issue.

**Closed by junegunn** 2016-02-26 15:47 UTC

**Comment by kwinczek** [comment] 2016-02-26 18:39
No problem @junegunn. Thanks for looking into it anyway! Did set up plug to use enew and problem is gone now. Well…

**Comment by mhinz** [comment] 2016-02-26 18:54
@kwinczek FWIW, this works just as well.

```vim
autocmd User Startified setlocal buflisted
```

It might break other plugins though, which is the reason I use `nobuflisted` in the first place.

I didn't know about `g:plug_window` so far, but setting it to `tabnew` works well for me.

**Comment by nhooyr** [comment] 2016-03-04 06:58
setting `g:plug_window` to `enew`? But it won't split then? That doesn't really solve the problem does it? 

For now @mhinz solution works well.

**Comment by junegunn** [comment] 2016-03-04 07:06
We didn't "solve" the issue but instead suggested a few workarounds. As pointed above, the root cause of the problem is an odd behavior of Vim which may or may not be a bug. A proper workaround for this "behavior" will not be as trivial as I'd like it to be, so I decided not to do it.

**Comment by mhinz** [comment] 2016-03-04 09:51
@nhooyr Technically `q` works, it's just that the Startify buffer is gone by then.

I added a FAQ to Startify: https://github.com/mhinz/vim-startify/commit/44f876f4e9c95d86033257fcd85f71fc4d5f90d0
