### ISSUE TITLE
PlugDiff with vim-startify

### ISSUE THREAD

**Issue by nhooyr** [junegunn/vim-plug#437] opened 2016-03-03 23:17 UTC
Explain the problem here ...

With mhinz/vim-startify installed if I open a new neovim instance and I run `:PlugUpdate` followed by pressing `D` for the differences. The screen looks like this:

<img width="1440" alt="screen shot 2016-03-03 at 6 16 00 pm" src="https://cloud.githubusercontent.com/assets/10180857/13512974/ff203878-e16b-11e5-93de-884b5ffe4f8e.png">

As you can see there is a random empty second window.

------------------------------

```
NVIM v0.1.3-244-g3e0fab6
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector
-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160227-5566-ze7f7v/build/config -I/tmp/neovim20160227-5566-ze7f7v/src -I/tmp/neovim20160227-5566-ze7f7v/dep
s-build/usr/include -I/tmp/neovim20160227-5566-ze7f7v/deps-build/usr/include -I/tmp/neovim20160227-5566-ze7f7v/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160227-5566-ze7f7v/deps-build/usr/include -I
/tmp/neovim20160227-5566-ze7f7v/deps-build/usr/include -I/tmp/neovim20160227-5566-ze7f7v/deps-build/usr/include -I/tmp/neovim20160227-5566-ze7f7v/deps-build/usr/include -I/usr/local/opt/gettext/include -I
/usr/include -I/usr/include -I/tmp/neovim20160227-5566-ze7f7v/build/src/nvim/auto -I/tmp/neovim20160227-5566-ze7f7v/build/include
Compiled by nhooyr@aubble

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment] 2016-03-04 06:38
Hi, this is a duplicate of #426.

**Closed by junegunn** 2016-03-04 06:38 UTC
