### ISSUE TITLE
Error detected while processing function <SNR>6_clean[13]..<SNR>6_git_validate[36]..<SNR>6_system[30]..function <SNR>6_clean[13]..<SNR>6_git_validate[36]..<SNR>6_system:

### ISSUE THREAD

**Issue by Chaitanyabsprip** [junegunn/vim-plug#1045] opened 2020-12-13 20:40 UTC
VIM
![image](https://user-images.githubusercontent.com/55058351/102023043-cc88fc00-3db0-11eb-8435-6a10ff4cc32e.png)

NVIM
![image](https://user-images.githubusercontent.com/55058351/102023071-f5a98c80-3db0-11eb-8ec3-6dcd6aef485c.png)

I don't know whether they are two different issues or not, but they both started at the same time.
Also, :PlugUpgrade says it can't write the the temp file in temp dir.
![image](https://user-images.githubusercontent.com/55058351/102023135-59cc5080-3db1-11eb-82ef-641b293af37f.png)

------------------------------

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 10 2020 23:03:23)
MS-Windows 64-bit console version
Included patches: 1-2127
Compiled by appveyor@APPVYR-WIN
Huge version without GUI.  Features included (+) or not (-):
+acl                +ex_extra           +multi_lang         +tcl/dyn
+arabic             +extra_search       +mzscheme/dyn       +termguicolors
+autocmd            -farsi              -netbeans_intg      +terminal
+autochdir          +file_in_path       +num64              -termresponse
+autoservername     +find_in_path       +packages           +textobjects
-balloon_eval       +float              +path_extra         +textprop
+balloon_eval_term  +folding            +perl/dyn           -tgetent
-browse             -footer             +persistent_undo    +timers
++builtin_terms     +gettext/dyn        +popupwin           +title
+byte_offset        -hangul_input       -postscript         -toolbar
+channel            +iconv/dyn          +printer            +user_commands
+cindent            +insert_expand      +profile            +vartabs
+clientserver       +ipv6               +python/dyn         +vertsplit
+clipboard          +job                +python3/dyn        +virtualedit
+cmdline_compl      +jumplist           +quickfix           +visual
+cmdline_hist       +keymap             +reltime            +visualextra
+cmdline_info       +lambda             +rightleft          +viminfo
+comments           +langmap            +ruby/dyn           +vreplace
+conceal            +libcall            +scrollbind         +vtp
+cryptv             +linebreak          +signs              +wildignore
+cscope             +lispindent         +smartindent        +wildmenu
+cursorbind         +listcmds           +sound              +windows
+cursorshape        +localmap           +spell              +writebackup
+dialog_con         +lua/dyn            +startuptime        -xfontset
+diff               +menu               +statusline         -xim
+digraphs           +mksession          -sun_workshop       -xpm_w32
-dnd                +modify_fname       +syntax             -xterm_save
-ebcdic             +mouse              +tag_binary
+emacs_tags         -mouseshape         -tag_old_static
+eval               +multi_byte_ime/dyn -tag_any_white
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL -DFEAT_IPV6      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python38.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DRUBY_VERSION=24 -DFEAT_HUGE /Fd.\ObjCULYHTRZAMD64/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64   libcmt.lib  user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python38.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib Ws2_32.lib /PDB:vim.pdb -debug

===================================================================================

NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by janlazo** [comment] 2021-01-17 17:54
Treating this as a duplicate of #852, #919.

Reopen if this is a different issue.

**Closed by janlazo** 2021-01-17 17:54 UTC
