### ISSUE TITLE
[help/feature] is there a way to allow load plugin instantly not lazily?

### ISSUE THREAD

**Issue by roachsinai** [junegunn/vim-plug#1066] opened 2021-02-02 08:15 UTC
First thanks a lot for this vim plugin manager!

## My problem

My problem is I use a vim plugin and the setting need using functions in autoload directory of that plugin. For now the setting of that plugin must after the statement `call plug#end()`, like below:

```
call plug#begin('~/.vim/plugged')
Plug 'user/plugin-name'
call plug#end()

" settings of plugin-name
call plugin-name#...
```

The expected behavior is enable call autoload function could work after `Plug 'user/plugin-name'`, again like below:

```
call plug#begin('~/.vim/plugged')
Plug 'user/plugin-name'
" settings of plugin-name
call plugin-name#...

call plug#end()
```

## Why I expect this

This enable you move

```
Plug 'user/plugin-name'
" settings of plugin-name
```

to a single file than source it in block of vim-plug.

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question

**Comment by j-hui** [comment] 2021-02-28 02:49
I have the same issue/question. Perhaps this could be implemented as a hook (similar to `'do'`)?

E.g.:

```
Plug 'user/plugin-name', { 'after' : function(plugin-name#...) }
```

**Comment by j-hui** [comment] 2021-02-28 03:16
Fwiw @roachsinai you can fake this by defining your own list of callbacks:

```viml
let g:plug_callbacks = []
call plug#begin('~/.vim/plugged')
"...
Plug 'user/plugin-name'
function! PluginCb
    call plugin-name#...
endfunction
let g:plug_callbacks += [function("PluginCb")]
" ...
call plug#end()
for Cb in g:plug_callbacks
    call Cb()
endfor
```

Note that `Cb` needs to be capitalized.

It's a little cumbersome, so it still would be nice to have this feature available (I might submit a PR if that's welcome). This is also useful for plugins that must be called after `plug#end()`, like deoplete's hooks and colorschemes.

**Comment by roachsinai** [comment] 2021-02-28 03:45
@j-hui thanks for reply!

I had use a function wrap that then call it after `plug#end`. And as you posted it's not so elegant.

**Comment by roachsinai** [comment] 2021-02-28 03:46
> I have the same issue/question. Perhaps this could be implemented as a hook (similar to `'do'`)?
> 
> E.g.:
> 
> ```
> Plug 'user/plugin-name', { 'after' : function(plugin-name#...) }
> ```

I do like this way, but how about a long function for `plugin-name#...` like below:

```
call textobj#user#plugin('datetime', {
\   'date': {
\     'pattern': '\<\d\d\d\d-\d\d-\d\d\>',
\     'select': ['ad', 'id'],
\   },
\   'time': {
\     'pattern': '\<\d\d:\d\d:\d\d\>',
\     'select': ['at', 'it'],
\   },
\ })
```

**Comment by j-hui** [comment] 2021-02-28 05:30
> how about a long function for

One way could be to wrap the long function invocation (and multiple function invocations) in another:

```viml
function TextObjHook
  call textobj#user#plugin('datetime', {
  \   'date': {
  \     'pattern': '\<\d\d\d\d-\d\d-\d\d\>',
  \     'select': ['ad', 'id'],
  \   },
  \   'time': {
  \     'pattern': '\<\d\d:\d\d:\d\d\>',
  \     'select': ['at', 'it'],
  \   },
  \ })
  " Other functions
endfunction
Plug 'user/plugin-name', { 'after' : function("TextObjHook") }
```

It's not that clean but it's at least cleaner than having to manipulate your own global array of functions. Also, the hook would only be run after the plugin has been installed (I only implemented my hack just now, and expect it to complain when I set up a new environment).

**Comment by roachsinai** [comment] 2021-02-28 10:00
@j-hui make a PR please~ 😃

**Comment by junegunn** [comment] 2021-02-28 11:58
Duplicate of #702. Please use the standard VimEnter autocmd.

```vim
Plug 'user/plugin-name'
autocmd VimEnter * call foo#bar()
```

**Closed by junegunn** 2021-02-28 11:58 UTC

**Comment by roachsinai** [comment] 2021-02-28 13:57
> Duplicate of #702. Please use the standard VimEnter autocmd.
> 
> ```viml
> Plug 'user/plugin-name'
> autocmd VimEnter * call foo#bar()
> ```

Hi @junegunn thanks for reply! And do you mean `dein#set_hook({plugins}, {hook-name}, {hook})` which did that as you posted in #702?

https://github.com/Shougo/dein.vim/blob/adac91b05ad9ef123d859edfe549ffde236f930c/doc/dein.txt#L407

**Comment by roachsinai** [comment] 2021-02-28 14:02
Seems it should be `dein#source`:

https://github.com/Shougo/dein.vim/blob/adac91b05ad9ef123d859edfe549ffde236f930c/doc/dein.txt#L1151

**Comment by j-hui** [comment] 2021-02-28 18:43
@junegunn thanks for pointing me to the duplicate issue! I'll chime in there.
