### ISSUE TITLE
Post hook failure with fzf (nvim)

### ISSUE THREAD

**Issue by ibhagwan** [junegunn/vim-plug#1070] opened 2021-02-07 05:39 UTC
When used with fzf & nvim, the install hook fails with the below error:

```
"Post-update hook for fzf ... /usr/share/nvim/runtime/install not found"
```

The relevant part from my `init.nvim`:

```
call plug#begin(stdpath('data') . '/plugged')

  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'

call plug#end()
```

When used with the below it works

```
call plug#begin(stdpath('data') . '/plugged')

  Plug 'junegunn/fzf', { 'do': 'yes \| ./install' }
  Plug 'junegunn/fzf.vim'

call plug#end()
```

nvim version:
```
:version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2  -g -U_FORTIFY_
SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-pr
ototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-stron
g -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -D
NVIM_UNIBI_HAS_VAR_FROM -I/builddir/neovim-0.4.4/build/config -I/builddir/neovim-0.4.4/src -I/usr/include -I/buildd
ir/neovim-0.4.4/build/src/nvim/auto -I/builddir/neovim-0.4.4/build/include
Compiled by void-buildslave@a-hel-fi

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by janlazo** [comment] 2021-02-19 02:45
Duplicate of https://github.com/junegunn/vim-plug/issues/964.

**Closed by janlazo** 2021-02-19 02:45 UTC
Labels: duplicate
