### ISSUE TITLE
Make vim-plug work with portable git

### ISSUE THREAD

**Issue by ordinary-slim** [junegunn/vim-plug#1012] opened 2020-09-04 12:55 UTC
I had a use case in which I wanted to setup vim on a machine to which I did not have admin rights. Installed portable versions of software , set my shell to git bash (the one that comes with portable git), commented out the _if_ check on `executable('git')`, works ok now.
This is a quick and dirty fix but maybe we could make it work in general ? I do not know if this is an often encountered use case though. 

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by janlazo** [comment] 2020-09-04 14:12
You don't need git for local plugins. You can suppress the errors via `silent! call plug#begin()`.

**Comment by ordinary-slim** [comment] 2020-09-04 14:30
The function `s:define_commands` of vim-plug stops if git is not in the path. That function is itself called by `plug#begin()`. If git is not needed, the fix is really easy then.

**Comment by janlazo** [comment] 2020-09-04 23:38
`Plug` is defined even if `git` is not executable. If you want the other commands to be defined, add `git` to your `PATH` before running (g)vim or before `plug#begin`.

**Comment by janlazo** [comment] 2020-09-07 01:19
Your issue is not with the lack of git in PATH but with how vim-plug does not define the rest of the commands if there are issues with the local environment. That is a separate enhancement issue and would require some error handling from `plug#begin` to the commands defined in `s:define_commands`. Open a new issue if you want this behavior. It is useful if the user wants to set some vim options after `plug#begin` and `plug#end`.

I am closing this issue because vim-plug is behaving as intended if `git` is unavailable.

**Closed by janlazo** 2020-09-07 01:19 UTC
Labels: windows
