### ISSUE TITLE
How to automate PlugInstall without having to run it manually inside Neovim?

### ISSUE THREAD

**Issue by trusktr** [junegunn/vim-plug#957] opened 2020-04-06 21:51 UTC
```
:version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict
-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_G
ENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src
 -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [x] OS X
    - [x] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [x] Neovim

I have a `dotfiles-repo/setup.sh` script that I normally run in my new OS installs. I set up my `.vimrc` file using `vim-plug`. Normally when I first run `nvim`, I manually run `:PlugInstall` to get everything set up.

But I am wondering if there is a way to automate this so I don't have to open nvim and manually run the command.

For example, I tried adding

```sh
nvim +PlugInstall
```

to my setup script, but that drops me into Neovim and requires hands-on.

How can I automate it in my bash script?

**Comment by janlazo** [comment] 2020-04-06 22:32
Duplicate of https://github.com/junegunn/vim-plug/issues/948

**Closed by janlazo** 2020-04-06 22:32 UTC
